---
apiVersion: sharedgpu.goc/v1
kind: SharePod
metadata:
  name: client1
  annotations:
    "sharedgpu/gpu_request": "0" # required if allocating GPU
    "sharedgpu/gpu_limit": "1" # required if allocating GPU
    "sharedgpu/gpu_mem": "1488490188" # required if allocating GPU # 1Gi, in bytes
    "sharedgpu/sched_affinity": "red" # optional
    #"sharedgpu/sched_anti-affinity": "green" # optional
    #"sharedgpu/sched_exclusion": "blue" # optional
spec:
  containers:
  - name: pytorch-test
    image: detectron2:latest
    imagePullPolicy: Never
    #command: ["sleep","10000"]       
    command: ["/bin/bash","-c"]
    args: [ " cd /home/cjobr/detectron2-0.3/  && python tools/benchmark.py --config-file  configs/COCO-Detection/faster_rcnn_R_50_FPN_1x.yaml --task eval"]
    volumeMounts:
    - mountPath: /home/cjobr
      name: test-volume
      #restartPolicy: OnFailure
  volumes:
  - name: test-volume
    hostPath:
      # directory location on host
      path: /home/cjobr
      # this field is optional
      type: Directory
  restartPolicy: OnFailure
