cellTypes:
  GTX1080-NODE:
    childCellType: "NVIDIA GeForce GTX 1080"
    childCellNumber: 2
    childCellPriority: 100
    isNodeLevel: true
  3-GTX1080-NODE:
    childCellType: GTX1080-NODE
    childCellNumber: 3
  RTX2070-NODE:
    childCellType: "NVIDIA GeForce RTX 2070"
    childCellNumber: 1
    childCellPriority: 200
    isNodeLevel: true

cells:
- cellType: 3-GTX1080-NODE
  cellChildren:
  - cellId: juno
  - cellId: apple
  - cellId: banana
- cellType: RTX2070-NODE
  cellId: cupid
