apiVersion: sharedgpu.goc/v1
kind: SharePod
metadata:
  name: shp3
  annotations:
    "sharedgpu/gpu_request": "0.4"
    "sharedgpu/gpu_limit": "1.0"
    "sharedgpu/gpu_mem": "3145728000"
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - name: cuda
    image: nvidia/cuda:9.0-base
    command: ["sh", "-c", "nvidia-smi -L; sleep infinity"]
